# Generated by Django 4.0.4 on 2022-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
